package main

import (
	"fmt"
	"os"
)

func main() {
	fileName := "/home/edward/projects/gosite/index.html"
	file, err := os.Create(fileName)
	if err != nil {
		fmt.Println("Error creating file:", err)
		return
	}
	defer file.Close()

    // define two variables at once
	title, backgroundColor := "The Go Site", "#222"

	content := `
<html>
    <head>
        <title>` + title + `</title>
        <style>
            body {
                background-color: ` + backgroundColor + `;
                color: #ccc;
                font-family: sans-serif;
                margin: 1rem;
            }                
            a {
                color: #dce378;
            }
        </style>
    </head>
<body>
    <h1>` + title + `</h1>
    <p>This file was generated by a Go script.</p>
    <p>Howto is here: <a href="https://tanguay-eu.vercel.app/forays/285" target="_blank">howto</a></p>
    <p>Here is the: <a href="https://github.com/edwardtanguay/et034-golang-site/blob/dev/gensite.go" target="_blank">repo</a></p>
    <p>Currently learning Go with this free, online book: <a target="_blank" href="https://www.programming-books.io/essential/go/basic-types-2803d5d5229f4932af82a1dcc86eb8bf">Essential Go</a>
     <p>Or try this one, seems more concise: <a href="https://gobyexample.com">https://gobyexample.com</a></p>

</body>
</html>
    `
	_, err = file.WriteString(content)
	if err != nil {
		fmt.Println("Error writing to file:", err)
		return
	}

	fmt.Println("File created and content written successfully.")
}
