package main

import (
	"fmt"
	"os"
)

func main() {
	fileName := "/var/www/go/index.html"
	file, err := os.Create(fileName)
	if err != nil {
		fmt.Println("Error creating file:", err)
		return
	}
	defer file.Close()

	content := `
<html>
    <head>
        <title>Go Site</title>
        <style>
            body {
                background-color: #333;
                color: #ccc;
                font-family: sans-serif;
                margin: 1rem;
            }                
            a {
                color: #dce378;
            }
        </style>
    </head>
<body>
    <h1>Go Site</h1>
    <p>This file was generated by a Go script.</p>
    <p>Currently learning Go with this free, online book: <a target="_blank" href="https://www.programming-books.io/essential/go/basic-types-2803d5d5229f4932af82a1dcc86eb8bf">Essential Go</a>
</body>
</html>
    `
	_, err = file.WriteString(content)
	if err != nil {
		fmt.Println("Error writing to file:", err)
		return
	}

	fmt.Println("File created and content written successfully.")
}
