package main

import (
	"fmt"
	"os"
)

func main() {
	fileName := "example.txt"
	file, err := os.Create(fileName)
	if err != nil {
		fmt.Println("Error creating file:", err)
		return
	}
	defer file.Close()

	content := `
<html>
    <head>
        <title>Golang Site</title>
    </head>
<body>
    <h1>Golang-generated Site</h1>
    <p>This file was generated by a Go script.</p>
</body>
</html>
    `
	_, err = file.WriteString(content)
	if err != nil {
		fmt.Println("Error writing to file:", err)
		return
	}

	fmt.Println("File created and content written successfully.")
}
